### ISSUE TITLE
KeyFormat breaks included relationships

### ISSUE THREAD

**Issue by juni0r** [jsonapi-rb/jsonapi-serializable#119]
`KeyFormat` breaks included relationships when the relationship's name is subject to key transformation. 

```ruby
class Resource < JSONAPI::Serializable::Resource
  extend JSONAPI::Serializable::Resource::KeyFormat
  key_format ->(key) { key.to_s.camelize(:lower) }
end
```

```ruby
class ContactResource < Resource
  type 'contacts'

  has_many :contact_groups

  attributes :first_name, :last_name, :email # , ...
end
```

```ruby
class ContactGroupResource < Resource
  type 'contactGroups'

  attributes :name
end
```

Results in the relationship key to be transformed but related resources don't get included:

```yaml
{
  "id": "046ffaf3-9c7b-4f36-a33b-1948cb889200",
  "type": "contacts",
  "attributes": {
    "firstName": "John",
    "lastName": "Doe",
    "email": 'john.doe@email.org'
  },
  "relationships": {
   "contactGroups": {
      "meta": {
        "included": false
      }
    }
  }
}
```

Without using `KeyFormat` it works as expected:

```yaml
{
  "id": "046ffaf3-9c7b-4f36-a33b-1948cb889200",
  "type": "contacts",
  "attributes": {
    "first_name": "John",
    "last_name": "Doe",
    "email": 'john.doe@email.org',
  },
  "relationships": {
    "contact_groups": {
      "data": [
        {
          "type": "contactGroups",
          "id": "c88e3a19-f814-49d9-a458-40c2103f0003"
        }
      ]
    }
  }
}
```
